### ISSUE TITLE
Windows vs Mac virtual environment setup issues.

### ISSUE THREAD

**Issue by sstryjak** [mikeckennedy/consuming_services_python_demos#3]
A Clean Environment For Our Course

Video instructions for:
. ./consuming_svc_env/bin/activate

State that in Windows the dot (.) is not needed however I found that more than that instruction was also required. The activate was not at this location. Rather it's nested in a /scripts/ folder (not bin) and for the windows cmd prompt I had to use \ instead of /.

Namely:
.\consuming_svc_env\scripts\activate.bat

Worked for me in Windows.

*Personal note and other windows users may have a similar issue:
  I also do not have access to a "which pip3" / "which pip" command (unrecognized command) even though I found a which.py file nested here:

C:\Users\sstry\AppData\Local\Programs\Python\Python36-32\Tools\scripts

And even added it to my environment variables. Still working on that one unless you have a suggestion?

**Comment by mikeckennedy** [comment]
Thanks for the extra info. I'll link to this from the home page on the repo or create a separate readme.

`which` is an unix command. The equivalent commend on Windows is `where` (I *think* I said that during  the presentation - meant to anyway).

Windows installers don't create an alias for python.exe -> python3.exe or pip.exe -> pip3.exe (super frustrating that they don't!). But you can create a batch file for each

`python3.bat`
```
# maybe use the full path to the python.exe file
python.exe
```

`pip3.bat`
```
 # maybe use the full path to the pip.exe file
pip.exe

```

**Comment by mikeckennedy** [comment]
Here you go:

https://github.com/mikeckennedy/consuming_services_python_demos/blob/master/venv_on_windows.md
